import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import { MoneyProvider } from '../contexts/MoneyContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sone Racing",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <MoneyProvider>
              {children}
          </MoneyProvider>
          </SessionProvider>
      </body>
    </html>
  );
}
